# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDVRform.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget
import json

class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):

        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 591)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ch10 = QtWidgets.QLineEdit(Dialog)
        self.ch10.setObjectName("ch10")
        self.gridLayout.addWidget(self.ch10, 14, 2, 1, 1)
        self.label_ch12 = QtWidgets.QLabel(Dialog)
        self.label_ch12.setObjectName("label_ch12")
        self.gridLayout.addWidget(self.label_ch12, 16, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 21, 0, 1, 1)
        self.ch8 = QtWidgets.QLineEdit(Dialog)
        self.ch8.setObjectName("ch8")
        self.gridLayout.addWidget(self.ch8, 12, 2, 1, 1)
        self.ch4 = QtWidgets.QLineEdit(Dialog)
        self.ch4.setObjectName("ch4")
        self.gridLayout.addWidget(self.ch4, 8, 2, 1, 1)
        self.label_ch3 = QtWidgets.QLabel(Dialog)
        self.label_ch3.setObjectName("label_ch3")
        self.gridLayout.addWidget(self.label_ch3, 7, 0, 1, 1)
        self.ch9 = QtWidgets.QLineEdit(Dialog)
        self.ch9.setObjectName("ch9")
        self.gridLayout.addWidget(self.ch9, 13, 2, 1, 1)
        self.ch13 = QtWidgets.QLineEdit(Dialog)
        self.ch13.setObjectName("ch13")
        self.gridLayout.addWidget(self.ch13, 17, 2, 1, 1)
        self.ch3 = QtWidgets.QLineEdit(Dialog)
        self.ch3.setObjectName("ch3")
        self.gridLayout.addWidget(self.ch3, 7, 2, 1, 1)
        self.label_ch10 = QtWidgets.QLabel(Dialog)
        self.label_ch10.setObjectName("label_ch10")
        self.gridLayout.addWidget(self.label_ch10, 14, 0, 1, 1)
        self.label_ch4 = QtWidgets.QLabel(Dialog)
        self.label_ch4.setObjectName("label_ch4")
        self.gridLayout.addWidget(self.label_ch4, 8, 0, 1, 1)
        self.ch7 = QtWidgets.QLineEdit(Dialog)
        self.ch7.setObjectName("ch7")
        self.gridLayout.addWidget(self.ch7, 11, 2, 1, 1)
        self.ch15 = QtWidgets.QLineEdit(Dialog)
        self.ch15.setObjectName("ch15")
        self.gridLayout.addWidget(self.ch15, 19, 2, 1, 1)
        self.label_ch16 = QtWidgets.QLabel(Dialog)
        self.label_ch16.setObjectName("label_ch16")
        self.gridLayout.addWidget(self.label_ch16, 20, 0, 1, 1)
        self.label_ch1 = QtWidgets.QLabel(Dialog)
        self.label_ch1.setObjectName("label_ch1")
        self.gridLayout.addWidget(self.label_ch1, 4, 0, 1, 1)
        self.ch1 = QtWidgets.QLineEdit(Dialog)
        self.ch1.setObjectName("ch1")
        self.gridLayout.addWidget(self.ch1, 4, 2, 1, 1)
        self.DVRname = QtWidgets.QLineEdit(Dialog)
        self.DVRname.setObjectName("DVRname")
        self.gridLayout.addWidget(self.DVRname, 0, 2, 1, 1)
        self.label_ch11 = QtWidgets.QLabel(Dialog)
        self.label_ch11.setObjectName("label_ch11")
        self.gridLayout.addWidget(self.label_ch11, 15, 0, 1, 1)
        self.label_ch5 = QtWidgets.QLabel(Dialog)
        self.label_ch5.setObjectName("label_ch5")
        self.gridLayout.addWidget(self.label_ch5, 9, 0, 1, 1)
        self.label_ch7 = QtWidgets.QLabel(Dialog)
        self.label_ch7.setObjectName("label_ch7")
        self.gridLayout.addWidget(self.label_ch7, 11, 0, 1, 1)
        self.label_ch9 = QtWidgets.QLabel(Dialog)
        self.label_ch9.setObjectName("label_ch9")
        self.gridLayout.addWidget(self.label_ch9, 13, 0, 1, 1)
        self.ch6 = QtWidgets.QLineEdit(Dialog)
        self.ch6.setObjectName("ch6")
        self.gridLayout.addWidget(self.ch6, 10, 2, 1, 1)
        self.label_ch8 = QtWidgets.QLabel(Dialog)
        self.label_ch8.setObjectName("label_ch8")
        self.gridLayout.addWidget(self.label_ch8, 12, 0, 1, 1)
        self.ch16 = QtWidgets.QLineEdit(Dialog)
        self.ch16.setObjectName("ch16")
        self.gridLayout.addWidget(self.ch16, 20, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ch0 = QtWidgets.QLineEdit(Dialog)
        self.ch0.setObjectName("ch0")
        self.gridLayout.addWidget(self.ch0, 3, 2, 1, 1)
        self.label_ch13 = QtWidgets.QLabel(Dialog)
        self.label_ch13.setObjectName("label_ch13")
        self.gridLayout.addWidget(self.label_ch13, 17, 0, 1, 1)
        self.ch14 = QtWidgets.QLineEdit(Dialog)
        self.ch14.setObjectName("ch14")
        self.gridLayout.addWidget(self.ch14, 18, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 30, 0, 1, 3)
        self.label_ch14 = QtWidgets.QLabel(Dialog)
        self.label_ch14.setObjectName("label_ch14")
        self.gridLayout.addWidget(self.label_ch14, 18, 0, 1, 1)
        self.ch2 = QtWidgets.QLineEdit(Dialog)
        self.ch2.setObjectName("ch2")
        self.gridLayout.addWidget(self.ch2, 6, 2, 1, 1)
        self.label_ch6 = QtWidgets.QLabel(Dialog)
        self.label_ch6.setObjectName("label_ch6")
        self.gridLayout.addWidget(self.label_ch6, 10, 0, 1, 1)
        self.ch12 = QtWidgets.QLineEdit(Dialog)
        self.ch12.setObjectName("ch12")
        self.gridLayout.addWidget(self.ch12, 16, 2, 1, 1)
        self.label_ch2 = QtWidgets.QLabel(Dialog)
        self.label_ch2.setObjectName("label_ch2")
        self.gridLayout.addWidget(self.label_ch2, 5, 0, 2, 1)
        self.ch11 = QtWidgets.QLineEdit(Dialog)
        self.ch11.setObjectName("ch11")
        self.gridLayout.addWidget(self.ch11, 15, 2, 1, 1)
        self.ch5 = QtWidgets.QLineEdit(Dialog)
        self.ch5.setObjectName("ch5")
        self.gridLayout.addWidget(self.ch5, 9, 2, 1, 1)
        self.label_ch15 = QtWidgets.QLabel(Dialog)
        self.label_ch15.setObjectName("label_ch15")
        self.gridLayout.addWidget(self.label_ch15, 19, 0, 1, 1)
        self.label_ch0 = QtWidgets.QLabel(Dialog)
        self.label_ch0.setObjectName("label_ch0")
        self.gridLayout.addWidget(self.label_ch0, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ADD NEW DVR"))
        self.label_ch12.setText(_translate("Dialog", "Channel 12"))
        self.label_ch3.setText(_translate("Dialog", "Channel 3"))
        self.label_ch10.setText(_translate("Dialog", "Channel 10"))
        self.label_ch4.setText(_translate("Dialog", "Channel 4"))
        self.label_ch16.setText(_translate("Dialog", "Channel 16"))
        self.label_ch1.setText(_translate("Dialog", "Channel 1"))
        self.label_ch11.setText(_translate("Dialog", "Channel 11"))
        self.label_ch5.setText(_translate("Dialog", "Channel 5"))
        self.label_ch7.setText(_translate("Dialog", "Channel 7"))
        self.label_ch9.setText(_translate("Dialog", "Channel 9"))
        self.label_ch8.setText(_translate("Dialog", "Channel 8"))
        self.label.setText(_translate("Dialog", "DVR Name"))
        self.label_ch13.setText(_translate("Dialog", "Channel 13"))
        self.label_ch14.setText(_translate("Dialog", "Channel 14"))
        self.label_ch6.setText(_translate("Dialog", "Channel 6"))
        self.label_ch2.setText(_translate("Dialog", "Channel 2"))
        self.label_ch15.setText(_translate("Dialog", "Channel 15"))
        self.label_ch0.setText(_translate("Dialog", "Channel 0"))

    def submitform(self):
        f = open( 'data/Channellink.json' )
        self.list_dump = json.load( f )
        # print(self.list_dump)
        f.close()


        self.key = self.DVRname.text()
        self.arr = list()
        self.arr.append(self.ch0.text())
        self.arr.append( self.ch1.text())
        self.arr.append(self.ch2.text())
        self.arr.append(self.ch3.text())
        self.arr.append(self.ch4.text())
        self.arr.append( self.ch5.text())
        self.arr.append(self.ch6.text())
        self.arr.append(self.ch7.text())
        self.arr.append( self.ch8.text())
        self.arr.append(self.ch9.text())
        self.arr.append(self.ch10.text())
        self.arr.append(self.ch11.text())
        self.arr.append( self.ch12.text())
        self.arr.append( self.ch13.text())
        self.arr.append(self.ch14.text())
        self.arr.append(self.ch15.text())
        self.arr.append( self.ch16.text())

        self.dict = {self.key: self.arr}
        self.list_dump[0].update(self.dict)
        # print( self.list_dump )
        f = open('data/Channellink.json','w')
        self.list_dump = json.dumps(self.list_dump )

        f.write(self.list_dump)
        f.close()







        # if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())

